# KPI Framework

## Purpose

This document defines the core business metrics used by the
Retail Energy BI platform.

The objective is to establish consistent and reusable metric definitions
across dashboards and analytical workflows.

---

# Portfolio KPIs

## 1. Total Revenue

### Definition

Total recognized revenue generated by the retail energy portfolio.

### Formula

```text
Total Revenue = SUM(Revenue)
